### ISSUE TITLE
undefined method `find' for Wikipedia:Module (NoMethodError)

### ISSUE THREAD

**Issue by jeremysklarsky** [kenpratt/wikipedia-client#44]
`<main>': undefined method`find' for Wikipedia:Module (NoMethodError)

I'm trying to duplicate the example in the docs, but get a no method error for `find`.

My code is simple.

**Comment by harman28** [comment]
@jeremysklarsky How were you able to fix this?

**Comment by harman28** [comment]
Figured it out, adding this for future reference if someone else comes searching.
You need to add `gem 'wikipedia-client'` to your Gemfile, and not `gem 'wikipedia'`. I was adding the latter, which is a completely different gem!

**Comment by pietromenna** [comment]
Hi @harman28 ,

This seems to be a problem in the example in the main page. Can you send a Pull Request fixing the example? I would be happy to merge it.

**Comment by harman28** [comment]
@pietromenna Not sure what you mean. The README already has this line, and it seems correct.

**Comment by pietromenna** [comment]
@harman28 You are right. The idea is to better document how to generate projects which uses this gem. I will figure out how to add this information. Thanks!

**Comment by analogdash** [comment]
Can anyone help? I'm still getting this problem. I have 
`gem 'wikipedia-client`
in my gemfile and bundle finds the correct gem but when I try it in rails console, I still get the NoMethodError

strangely enough, running
`require 'wikipedia'`
makes it work.

**Comment by pietromenna** [comment]
Hi @analogdash ,

The way you are using is actually the correct way to use it. In order to install, you need to install `wikipedia-client`gem. To do this, you added to your `Gemfile` and did a `bundle install`. The reference is [here](https://github.com/kenpratt/wikipedia-client#installation)

Now, to consume you must follow what is in the examples. The correct way is `require wikipedia`. The example is [here](https://github.com/kenpratt/wikipedia-client#examples)
